spring.application.name=job4j_social_media_api

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/social_media
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# ????????????? ???????? liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/dbchangelog.xml

# ???? DataSource
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG

# ?????????? SQL ????? ???????????
spring.liquibase.show-summary-output=all

# ???????????? ??????? ??????????? ??? Liquibase
logging.level.liquibase=TRACE
logging.level.liquibase.core=TRACE
logging.level.liquibase.changelog=TRACE
logging.level.liquibase.resource=TRACE
logging.level.liquibase.parser=TRACE

# ???? Spring Boot ??? Liquibase
logging.level.org.springframework.boot.autoconfigure.liquibase=DEBUG

# ???????? ??? ???????????????? ??? ??????
debug=true